// frontend/src/app/features/dashboard/dashboard.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { RouterLink } from '@angular/router';
import { ApiService } from '../../core/http/api.service';
import { AuthService } from '../../core/auth/auth.service';
import { Campaign } from '../../core/models/models';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [RouterLink],
  template: `
    <div class="page-pad">
      <div class="page-header">
        <div>
          <h1>Good morning, {{ auth.currentUser()?.name?.split(' ')[0] || 'there' }}</h1>
          <p class="subtitle">{{ activeCampaigns.length }} active campaign(s) · {{ totalAssignments }} assignments in flight</p>
        </div>
        <div class="header-actions">
          <button class="btn btn-ghost">
            <i class="pi pi-download"></i> Export
          </button>
          <a class="btn btn-accent" routerLink="/campaigns/new">
            <i class="pi pi-plus"></i> New campaign
          </a>
        </div>
      </div>

      <!-- KPI Strip -->
      <div class="kpi-grid">
        @for (kpi of kpis; track kpi.label) {
          <div class="kpi-card card">
            <div class="kpi-icon" [style.color]="kpi.color">
              <i [class]="'pi ' + kpi.icon"></i>
            </div>
            <div class="kpi-label">{{ kpi.label }}</div>
            <div class="kpi-value" [style.color]="kpi.color">{{ kpi.value }}</div>
            <div class="kpi-trend">{{ kpi.trend }}</div>
          </div>
        }
      </div>

      <!-- Active Campaigns -->
      <div class="section-header">
        <h2>Active campaigns</h2>
        <a class="btn btn-ghost btn-sm" routerLink="/campaigns">View all <i class="pi pi-chevron-right"></i></a>
      </div>

      <div class="campaigns-grid">
        @for (c of activeCampaigns; track c.id) {
          <a class="campaign-card card" [routerLink]="['/campaigns', c.id]">
            <div class="campaign-header">
              <div>
                <div class="campaign-name">{{ c.name }}</div>
                <div class="campaign-meta">{{ c.sla_days }}d SLA</div>
              </div>
            </div>
            <div class="campaign-progress-bar">
              <div class="progress-fill accent" style="width: 36%"></div>
            </div>
            <div class="campaign-footer">
              <span><i class="pi pi-calendar"></i> Due {{ formatDate(c.due_date) }}</span>
              <span class="badge active">Active</span>
            </div>
          </a>
        }
        @if (activeCampaigns.length === 0 && !loading) {
          <div class="empty">No active campaigns. <a routerLink="/campaigns/new">Create one</a>.</div>
        }
      </div>
    </div>
  `,
  styles: [`
    .page-header { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 24px; }
    .subtitle { color: var(--ink-4); font-size: 14px; margin-top: 4px; }
    .header-actions { display: flex; gap: 8px; }

    .kpi-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin-bottom: 28px; }
    .kpi-card { padding: 16px; }
    .kpi-icon { font-size: 18px; margin-bottom: 8px; }
    .kpi-label { font-size: 11px; text-transform: uppercase; letter-spacing: .04em; color: var(--ink-4); font-weight: 500; margin-bottom: 4px; }
    .kpi-value { font-size: 28px; font-weight: 600; letter-spacing: -0.02em; }
    .kpi-trend { font-size: 11px; color: var(--ink-4); margin-top: 4px; }

    .section-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 12px; }
    .campaigns-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; }
    .campaign-card { padding: 18px; cursor: pointer; text-decoration: none; display: block; transition: box-shadow .15s, border-color .15s; color: inherit; }
    .campaign-card:hover { border-color: var(--border-strong); box-shadow: var(--shadow-md); }
    .campaign-header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 14px; }
    .campaign-name { font-weight: 600; color: var(--ink-1); font-size: 15px; margin-bottom: 2px; }
    .campaign-meta { font-size: 12px; color: var(--ink-4); }
    .campaign-progress-bar { height: 8px; background: var(--surface-3); border-radius: 4px; overflow: hidden; margin-bottom: 12px; }
    .progress-fill { height: 100%; border-radius: 4px; }
    .accent { background: var(--accent); }
    .campaign-footer { display: flex; justify-content: space-between; align-items: center; font-size: 12px; color: var(--ink-4); }
    .badge { padding: 2px 8px; border-radius: 999px; font-size: 11px; font-weight: 500; }
    .badge.active { background: var(--accent-soft); color: var(--accent-ink); }
    .empty { color: var(--ink-4); font-size: 14px; padding: 24px 0; }

    .btn { display: inline-flex; align-items: center; gap: 6px; height: 36px; padding: 0 14px; border-radius: var(--r-md); font-family: inherit; font-size: 13px; font-weight: 500; cursor: pointer; border: 1px solid transparent; text-decoration: none; transition: background .12s; }
    .btn-ghost { background: transparent; color: var(--ink-2); }
    .btn-ghost:hover { background: var(--surface-3); }
    .btn-accent { background: var(--accent); color: #fff; border: none; }
    .btn-accent:hover { background: var(--accent-hover); }
    .btn-sm { height: 28px; padding: 0 10px; font-size: 12px; }
  `],
})
export class DashboardComponent implements OnInit {
  auth = inject(AuthService);
  private api = inject(ApiService);

  campaigns: Campaign[] = [];
  loading = true;

  get activeCampaigns() { return this.campaigns.filter(c => c.status === 'active'); }
  get totalAssignments() { return this.activeCampaigns.reduce((sum) => sum + 142, 0); }

  kpis = [
    { label: 'Active campaigns', value: '0', trend: 'Loading…', color: 'var(--accent)', icon: 'pi-flag' },
    { label: 'Assignments', value: '—', trend: '—', color: 'var(--ink-1)', icon: 'pi-list' },
    { label: 'Approved', value: '—', trend: '—', color: 'var(--positive)', icon: 'pi-check' },
    { label: 'SLA breaches', value: '—', trend: 'Needs attention', color: 'var(--danger)', icon: 'pi-exclamation-triangle' },
  ];

  ngOnInit(): void {
    this.api.getCampaigns().subscribe({
      next: campaigns => {
        this.campaigns = campaigns;
        this.kpis[0].value = String(campaigns.filter(c => c.status === 'active').length);
        this.kpis[0].trend = `${campaigns.length} total`;
        this.loading = false;
      },
      error: () => { this.loading = false; },
    });
  }

  formatDate(d: string): string {
    return new Date(d).toLocaleDateString('en', { month: 'short', day: 'numeric' });
  }
}

// project/screens/dashboard.jsx
// Admin: Campaign overview dashboard
// ------------------------------------------------------------------
const ScreenDashboard = ({ onOpenCampaign, onNav }) => {
  const store = useStore();
  const activeCampaigns = store.campaigns.filter(c => c.status === 'active');
  const totalAssignments = activeCampaigns.reduce((a, c) => a + c.assignments, 0);
  const approvedTotal = activeCampaigns.reduce((a, c) => a + c.progress.approved, 0);
  const overdueTotal = activeCampaigns.reduce((a, c) => a + c.slaBreaches, 0);

  return (
    <PagePad>
      <div style={{ marginBottom: 20, display: 'flex', alignItems: 'flex-end', justifyContent: 'space-between' }}>
        <div>
          <h1 style={{ fontFamily: 'var(--font-serif)', fontSize: 34, fontWeight: 400, letterSpacing: '-0.01em', marginBottom: 2 }}>
            Good afternoon, Alex
          </h1>
          <div style={{ color: 'var(--ink-4)', fontSize: 14 }}>3 active campaigns · 319 assignments in flight</div>
        </div>
        <div style={{ display: 'flex', gap: 8 }}>
          <button className="btn btn-secondary"><Icon name="download" size={14} /> Export</button>
          <button className="btn btn-accent" onClick={() => onNav && onNav('campaigns', { createNew: true })}>
            <Icon name="plus" size={14} /> New campaign
          </button>
        </div>
      </div>

      {/* KPI row */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)', gap: 12, marginBottom: 20 }}>
        {[
          { label: 'Active campaigns',    value: '3',    trend: '+1 vs Q1',   color: 'var(--accent)',   icon: 'campaigns' },
          { label: 'Assignments total',   value: totalAssignments, trend: '265 active', color: 'var(--ink-1)', icon: 'assignments' },
          { label: 'Approved',            value: approvedTotal, trend: '26% complete', color: 'var(--positive)', icon: 'check' },
          { label: 'SLA breaches',        value: overdueTotal, trend: 'Needs attention', color: 'var(--danger)', icon: 'alert' },
        ].map((k, i) => (
          <div key={i} className="card" style={{ padding: 16 }}>
            <div style={{ display: 'flex', alignItems: 'flex-start', justifyContent: 'space-between', marginBottom: 12 }}>
              <div style={{ width: 30, height: 30, borderRadius: 8, background: 'var(--surface-2)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: k.color }}>
                <Icon name={k.icon} size={15} />
              </div>
            </div>
            <div style={{ fontSize: 11, color: 'var(--ink-4)', fontWeight: 500, marginBottom: 2, textTransform: 'uppercase', letterSpacing: '0.04em' }}>{k.label}</div>
            <div style={{ fontSize: 28, fontWeight: 600, letterSpacing: '-0.02em', color: 'var(--ink-1)' }} className="num">{k.value}</div>
            <div style={{ fontSize: 11, color: 'var(--ink-4)', marginTop: 4 }}>{k.trend}</div>
          </div>
        ))}
      </div>

      {/* Active campaigns */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 10 }}>
        <h2>Active campaigns</h2>
        <button className="btn btn-ghost btn-sm">View all <Icon name="chevronRight" size={12} /></button>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: 12, marginBottom: 24 }}>
        {activeCampaigns.map(c => {
          const t = totalsFor(c);
          return (
            <div key={c.id} className="card" style={{ padding: 18, cursor: 'pointer', transition: 'box-shadow .15s, border-color .15s' }}
              onClick={() => onOpenCampaign && onOpenCampaign(c.id)}
              onMouseEnter={(e) => { e.currentTarget.style.borderColor = 'var(--border-strong)'; e.currentTarget.style.boxShadow = 'var(--shadow-md)'; }}
              onMouseLeave={(e) => { e.currentTarget.style.borderColor = 'var(--border)'; e.currentTarget.style.boxShadow = 'none'; }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 14 }}>
                <div>
                  <div style={{ fontWeight: 600, color: 'var(--ink-1)', fontSize: 15, marginBottom: 2 }}>{c.name}</div>
                  <div style={{ fontSize: 12, color: 'var(--ink-4)' }}>{c.properties} properties · owned by {c.owner}</div>
                </div>
                {c.slaBreaches > 0 && (
                  <span className="badge badge-red">
                    <Icon name="alert" size={10} /> {c.slaBreaches} breach
                  </span>
                )}
              </div>

              <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 6, fontSize: 12, color: 'var(--ink-4)' }}>
                <span>{t.percent}% approved</span>
                <span className="mono num">{t.done} / {t.total}</span>
              </div>
              {/* stacked segmented progress */}
              <div style={{ display: 'flex', height: 8, borderRadius: 4, overflow: 'hidden', background: 'var(--surface-3)', marginBottom: 12 }}>
                {[
                  { k: 'approved', c: 'var(--positive)' },
                  { k: 'under_review', c: 'var(--warning)' },
                  { k: 'submitted', c: '#7B3FE4' },
                  { k: 'in_progress', c: 'var(--accent)' },
                  { k: 'rejected', c: 'var(--danger)' },
                ].map(seg => (
                  <div key={seg.k} style={{ width: `${(c.progress[seg.k] / t.total) * 100}%`, background: seg.c }} />
                ))}
              </div>

              <div style={{ display: 'flex', gap: 16, fontSize: 12, flexWrap: 'wrap' }}>
                <span style={{ color: 'var(--ink-4)', display: 'inline-flex', alignItems: 'center', gap: 4 }}>
                  <Icon name="calendar" size={12} /> Due {new Date(c.dueDate).toLocaleDateString('en', { month: 'short', day: 'numeric' })}
                </span>
                <span style={{ color: 'var(--ink-4)', display: 'inline-flex', alignItems: 'center', gap: 4 }}>
                  <Icon name="clock" size={12} /> T+{c.slaDays} SLA
                </span>
                <span style={{ color: 'var(--ink-4)', display: 'inline-flex', alignItems: 'center', gap: 4 }}>
                  <Icon name="users" size={12} /> 4 assignees
                </span>
              </div>
            </div>
          );
        })}
      </div>

      {/* Two-col: activity + upcoming breaches */}
      <div style={{ display: 'grid', gridTemplateColumns: '1.4fr 1fr', gap: 12 }}>
        <div className="card" style={{ padding: 18 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
            <h3>Recent activity</h3>
            <button className="btn btn-ghost btn-sm">All events</button>
          </div>
          {[
            { icon: 'check', color: 'var(--positive)', text: <><b>Priya Shah</b> approved <span className="mono">1200 Commerce Way</span></>, time: '2m ago' },
            { icon: 'send', color: 'var(--accent)', text: <><b>Ben Torres</b> submitted values for <span className="mono">Harbor Blvd · Long Beach</span></>, time: '14m ago' },
            { icon: 'alert', color: 'var(--danger)', text: <>SLA breached for <span className="mono">Glacier Way · Anchorage</span></>, time: '1h ago' },
            { icon: 'mail', color: 'var(--warning)', text: <>Reminder sent to <b>12 assignees</b> · EMEA Q2</>, time: '3h ago' },
            { icon: 'link', color: 'var(--ink-3)', text: <><b>Alex Morgan</b> issued 4 external signed links</>, time: '5h ago' },
          ].map((a, i) => (
            <div key={i} style={{ display: 'flex', gap: 12, padding: '10px 0', borderBottom: i < 4 ? '1px solid var(--divider)' : 'none', alignItems: 'center' }}>
              <div style={{ width: 28, height: 28, borderRadius: 14, background: 'var(--surface-2)', display: 'flex', alignItems: 'center', justifyContent: 'center', color: a.color, flexShrink: 0 }}>
                <Icon name={a.icon} size={13} />
              </div>
              <div style={{ flex: 1, fontSize: 13, color: 'var(--ink-2)' }}>{a.text}</div>
              <div style={{ fontSize: 11, color: 'var(--ink-4)' }}>{a.time}</div>
            </div>
          ))}
        </div>

        <div className="card" style={{ padding: 18 }}>
          <div style={{ marginBottom: 12 }}>
            <h3>Upcoming SLA</h3>
            <div style={{ fontSize: 12, color: 'var(--ink-4)', marginTop: 2 }}>Assignments due this week</div>
          </div>
          {store.assignments.filter(a => a.daysRemaining <= 5 && a.daysRemaining >= -3 && !['approved', 'rejected'].includes(a.status)).slice(0, 5).map((a, i, arr) => (
            <div key={a.id} style={{ display: 'flex', gap: 10, padding: '10px 0', borderBottom: i < arr.length - 1 ? '1px solid var(--divider)' : 'none', alignItems: 'center' }}>
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ fontSize: 13, fontWeight: 500, color: 'var(--ink-1)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{a.property.address}</div>
                <div style={{ fontSize: 11, color: 'var(--ink-4)' }}>{a.assignee}</div>
              </div>
              <span className={'badge ' + (a.daysRemaining < 0 ? 'badge-red' : a.daysRemaining <= 2 ? 'badge-amber' : 'badge-gray')} style={{ fontSize: 10 }}>
                {a.daysRemaining < 0 ? `${-a.daysRemaining}d late` : `${a.daysRemaining}d left`}
              </span>
            </div>
          ))}
        </div>
      </div>
    </PagePad>
  );
};

Object.assign(window, { ScreenDashboard });
